trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - 'docs/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: goVersion
    value: '1.13'
  - name: goBuiltAppName
    value: 'main'
  - name: nodejsVersion
    value: '13.x'
  - name: dockerVersion
    value: '19.03.9'
  - name: herokuRegistry
    value: 'registry.heroku.com'
  - name: herokuApp
    value: 'exteross'
  - name: branchMainChanged
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: branchHerokuChanged
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/heroku-build') }}
  - name: branchDockerHubChanged
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/dockerhub-build') }}
  - name: branchIdBtnguyen2kChanged
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/id.btnguyen2k-build') }}
  - group: Release
